### ISSUE TITLE
Have you achieved good results using 3D Scanning Software by Moreno, Taubin?

### ISSUE THREAD

**Issue by mambro** [HeuristicLabs/lze_scan3d#1]
Hi, I am an italian research scholar. I'm working on Projective Augmented Reality with a robotic head. Unfortunately, I still have problems with Camera (I'm using a Kinect One) - Projector calibration.

I have conveniently modified the promising 3D Scanning Software to make it able to work with Kinect One but there is something to change that avoids to achieve good results. Furthermore, I'm obtaining 
bad results also using webcams. I often encounter problems at the "decode" step, when the gray code structured light is detected ("ERROR: projector resolution does not match") . Finally, when I collected good image datasets, I've always obtained bad calibration results (for instance, the translation vector T shows very wrong numbers).

Have you used this tool obtaining good calibration values? How have you modified the original software?

Thank you in advance,

Michele Mambrini

**Comment by nickarmstrongcrews** [comment]
Yes, I got some reasonable results with the original software.

It has been a couple years since I used this, though... but I do recall seeing "projector resolution doesn't match." I believe you can tweak projector settings somewhere in the application?

I also recall that I needed far more than the minimum number of calibration images... maybe 30? It is important to get a diverse set of configurations (not just 30 images from the same exact angle). I also used a big checkerboard poster for calibration rather than a projector... makes it easy to rotate it around and also easy to pick out corners.
